program: tools/train_sweeps.py
entity: boostcamp-2th-cv-02team
project: object-detection-recycling-trash
method: grid
metric:
  name: val/bbox_mAP_50
  goal: maximize
parameters:
  config:
    value: configs/custom/models/htc/config.py
  lr:
    values: [0.001, 0.00001]
  wd:
    values: [0.005, 0.002]
